<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="L02205Q2H2" name="RestAssuredTests" tests="11" failures="3" timestamp="27 Apr 2020 22:57:18 GMT" time="29.451" errors="0">
  <testcase name="checkContentLength" time="0.002" classname="com.employeeapi.test.TC001_GetRequest"/>
  <testcase name="checkResponseBody" time="0.023" classname="com.employeeapi.test.TC001_GetRequest"/>
  <testcase name="checkResponseTime" time="0.002" classname="com.employeeapi.test.TC001_GetRequest"/>
  <testcase name="checkStatusLine" time="0.001" classname="com.employeeapi.test.TC001_GetRequest"/>
  <testcase name="checkResponseBody" time="0.004" classname="com.employeeapi.test.TC002_Get_OneEmp_Record"/>
  <testcase name="checkStatusCode" time="0.006" classname="com.employeeapi.test.TC002_Get_OneEmp_Record">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.employeeapi.test.TC002_Get_OneEmp_Record.checkStatusCode(TC002_Get_OneEmp_Record.java:41)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkResponseBody" time="0.002" classname="com.employeeapi.test.TC003_Post_Emp_Record"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.employeeapi.test.TC003_Post_Emp_Record"/>
  <testcase name="checkResponseBody" time="0.001" classname="com.employeeapi.test.TC004_Put_EmpRecord">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.employeeapi.test.TC004_Put_EmpRecord.checkResponseBody(TC004_Put_EmpRecord.java:50)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase name="checkStatusCode" time="0.001" classname="com.employeeapi.test.TC004_Put_EmpRecord"/>
  <testcase name="checkResponseBody" time="0.001" classname="com.employeeapi.test.TC005_Delete_Emp_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.employeeapi.test.TC005_Delete_Emp_Record.checkResponseBody(TC005_Delete_Emp_Record.java:38)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
</testsuite> <!-- RestAssuredTests -->
